name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          # this distribution is cached by github actions
          distribution: 'temurin'
          # jdk version to use, specified in pom.xml
          java-version: '21'
          # use the github actions cached jdk if available.
          check-latest: false
      - name: Package client jar
        id: package
        run: mvn -B clean package --file pom.xml --no-transfer-progress
      - name: Publish client artifact
        uses: ./.github/actions/upload_build
        if: ${{ always() && steps.package.outcome == 'success' }}
        with:
          SOURCE_FILE: 'target/opencraft-client.jar'
          DEST_NAME: 'opencraft-client.jar'
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          files: 'target/opencraft-client.jar'
