name: Deployment

on: [workflow_dispatch]

jobs:
  Build:
    name: Build
    environment:
      name: Build

    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: Ubuntu
            os: ubuntu-latest
          - platform: Windows
            os: windows-latest
          - platform: macOS
            os: macos-latest
    
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7
      - name: Build
        shell: bash
        run: echo "Building for ${{ matrix.platform}}"
      
