name: Download for Linux
on:
  push:
    branches:
      - '**'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-linux
  cancel-in-progress: true

jobs:
  x32:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Update submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive

      - name: Install packages
        shell: bash
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get -y update

          sudo apt-get -y install gcc-multilib cmake libglfw3-dev:i386 libglu1-mesa:i386 libglfw3:i386

      - name: Compile
        shell: bash
        id: compile
        run: |
          mkdir -p build
          cd build
          cmake .. -DTARGET_LINUX=ON -DTARGET_LINUX_32=ON
          cmake --build .

      - name: Upload artifact
        uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'bin/oc_linux32'
          DEST_NAME: 'OpenCraft-x32'

      - name: Notify success on Discord
        uses: ./.github/actions/build_notifier
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Tux.svg/640px-Tux.svg.png'
          title: 'Linux x32 Build'
          content: 'This workflow has **succeeded**.\\nClick [here](https://github.com/OpenCraft-Studios/opencraft/actions/workflows/linux.yml) to see the latest version.'
          color: 511007
          url: '${{ secrets.WEBHOOK_BUILD_SUCCESS_URL }}'

      - name: Notify failure on Discord
        uses: ./.github/actions/build_notifier
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Tux.svg/640px-Tux.svg.png'
          title: 'Linux x32 Build'
          content: 'This workflow has **failed**!\\nClick [here](https://github.com/OpenCraft-Studios/opencraft/actions/workflows/linux.yml) to see the latest version.'
          color: 16724016
          url: '${{ secrets.WEBHOOK_BUILD_FAILED_URL }}'

  x64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Update submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive

      - name: Install packages
        shell: bash
        run: |
          sudo apt-get -y update
          sudo apt-get -y install cmake libglfw3-dev

      - name: Compile
        shell: bash
        id: compile
        run: |
          mkdir -p build
          cd build
          cmake .. -DTARGET_LINUX=ON -DTARGET_LINUX_64=ON
          cmake --build .

      - name: Upload artifact
        uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'bin/oc_linux64'
          DEST_NAME: 'OpenCraft-x64'

      - name: Notify success on Discord
        uses: ./.github/actions/build_notifier
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Tux.svg/640px-Tux.svg.png'
          title: 'Linux x64 Build'
          content: 'This workflow has **succeeded**.\\nClick [here](https://github.com/OpenCraft-Studios/opencraft/actions/workflows/linux.yml) to see the latest version.'
          color: 511007
          url: '${{ secrets.WEBHOOK_BUILD_SUCCESS_URL }}'

      - name: Notify failure on Discord
        uses: ./.github/actions/build_notifier
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Tux.svg/640px-Tux.svg.png'
          title: 'Linux x64 Build'
          content: 'This workflow has **failed**!\\nClick [here](https://github.com/OpenCraft-Studios/opencraft/actions/workflows/linux.yml) to see the latest version.'
          color: 16724016
          url: '${{ secrets.WEBHOOK_BUILD_FAILED_URL }}'
