name: Download for Linux
on:
  push:
    branches:
      - '**'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-linux
  cancel-in-progress: true

jobs:
  x32:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        shell: bash
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get -y update
          sudo apt-get -y install gcc-multilib cmake
          sudo apt-get -y install lib32gcc-12-dev libx11-dev:i386 libxrandr-dev:i386 libxinerama-dev:i386 libxcursor-dev:i386 libxi-dev:i386

      - name: Compile GLFW (i386)
        shell: bash
        env:
          CFLAGS: -Werror -lm
          CXXFLAGS: -lm
          LDFLAGS: -lm
        run: |
          git clone --branch latest --single-branch https://github.com/glfw/glfw.git glfw-v3.4
          cd glfw-v3.4

          # Inject super hyper mega secret script
          sed -i '98i if (TARGET glfw)\n    target_link_libraries(glfw PRIVATE m)\nendif()' glfw-v3.4/CMakeLists.txt

          # Configure & build the static version (X11 @ 32 bits)
          cmake -B build-x11-static -S . -D GLFW_BUILD_EXAMPLES=OFF -D GLFW_BUILD_WAYLAND=OFF -D GLFW_BUILD_X11=ON -DCMAKE_C_FLAGS="-m32" -DCMAKE_CXX_FLAGS="-m32"
          cmake --build build-x11-static --parallel

          # Install the shared version
          sudo cmake --install build-x11-static

      - name: Compile
        shell: bash
        id: compile
        run: |
          mkdir -p build
          cd build
          cmake .. -DTARGET_LINUX=ON -DTARGET_LINUX_32=ON
          cmake --build .

      - name: Upload artifact
        uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'bin/oc_linux32'
          DEST_NAME: 'OpenCraft-x32'

      - name: Notify success on Discord
        uses: ./.github/actions/build_notifier
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Tux.svg/640px-Tux.svg.png'
          title: 'Linux x32 Build'
          content: 'This workflow has **succeeded**.\\nClick [here](https://github.com/OpenCraft-Studios/opencraft/actions/workflows/linux.yml) to see the latest version.'
          color: 511007
          url: '${{ secrets.WEBHOOK_BUILD_SUCCESS_URL }}'

      - name: Notify failure on Discord
        uses: ./.github/actions/build_notifier
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Tux.svg/640px-Tux.svg.png'
          title: 'Linux x32 Build'
          content: 'This workflow has **failed**!\\nClick [here](https://github.com/OpenCraft-Studios/opencraft/actions/workflows/linux.yml) to see the latest version.'
          color: 16724016
          url: '${{ secrets.WEBHOOK_BUILD_FAILED_URL }}'

  x64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install packages
        shell: bash
        run: |
          sudo apt-get -y update
          sudo apt-get -y install cmake libglfw3-dev

      - name: Compile
        shell: bash
        id: compile
        run: |
          mkdir -p build
          cd build
          cmake .. -DTARGET_LINUX=ON -DTARGET_LINUX_64=ON
          cmake --build .

      - name: Upload artifact
        uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'bin/oc_linux64'
          DEST_NAME: 'OpenCraft-x64'

      - name: Notify success on Discord
        uses: ./.github/actions/build_notifier
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Tux.svg/640px-Tux.svg.png'
          title: 'Linux x64 Build'
          content: 'This workflow has **succeeded**.\\nClick [here](https://github.com/OpenCraft-Studios/opencraft/actions/workflows/linux.yml) to see the latest version.'
          color: 511007
          url: '${{ secrets.WEBHOOK_BUILD_SUCCESS_URL }}'

      - name: Notify failure on Discord
        uses: ./.github/actions/build_notifier
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Tux.svg/640px-Tux.svg.png'
          title: 'Linux x64 Build'
          content: 'This workflow has **failed**!\\nClick [here](https://github.com/OpenCraft-Studios/opencraft/actions/workflows/linux.yml) to see the latest version.'
          color: 16724016
          url: '${{ secrets.WEBHOOK_BUILD_FAILED_URL }}'
