name: Test with Maven

# Do lots of tests :)
on:
  workflow_dispatch:
  pull_request:
    branches: [ main, master ]
  push:
    branches:
      - '**'        # matches every branch
      - '!master'   # excludes master
      - '!main'     # excludes main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          # this distribution is cached by github actions
          distribution: 'temurin'
          # jdk version to use, specified in pom.xml
          java-version: '21'
          # use the github actions cached jdk if available.
          check-latest: false
      - name: mvn test
        run: mvn clean test --file pom.xml --no-transfer-progress
